### ISSUE TITLE
Career planning and employment

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/Estonian-Open-Data-Issue-Tracker#16]
Idea from Tartu hackathon:

A career choice guide that would rely on long term projection of various industries' demand which would also help build relevant knowledge and plan education.

**Comment by andreskytt** [comment]
What do you mean by the projection? This assumes actually two things: that projection being there and that projection being available as open data. Current state, the best it is, is available at http://www.kutsekoda.ee/et/kutseregister/statistika

**Comment by andreskytt** [comment]
Hille, please take a look. Close, if the referenced data is OK
