### ISSUE TITLE
Write an API that can parse tax data

### ISSUE THREAD

**Issue by andreskytt** [okestonia/Estonian-Open-Data-Issue-Tracker#20]
EMTA publishes its tax data at http://www.emta.ee/et/kontaktid-ja-ametist/maksulaekumine-statistika/tasutud-maksud Huge ODT sheets, really hard to analyse. 

As a data user, I want to be able to access historical and current tax data for a particular company and query companies and paid taxes per quarter per municipality. 

For this, we need to build something that

- Polls the URL for new data published
- Downloads the data
- Makes it available via a RESTful API

**Comment by peepkungas** [comment]
Hello,
The mentioned functionality will be implemented by Register OÜ in the context of Open Data Plan offering (currently includes endpoints for /organizations, /sites, /locations and /contacts) of Register Graph API (see https://developers.ir.ee/graph-api for current API overview). I'll let you know once we have scheduled the functionality. You can get keys from https://developers.ir.ee/apis/.

**Comment by andreskytt** [comment]
Thanks to @peepkungas, the data is available. Closing

**Comment by boamaod** [comment]
Is this data also registered in some list, for example opendata.riik.ee?

**Comment by infokujur** [comment]
Ei ole opendata.riik.ee peal: https://opendata.riik.ee/et/publisher/maksu--ja-tolliamet
