### ISSUE TITLE
State Real Estate Register

### ISSUE THREAD

**Issue by tormi** [okestonia/Estonian-Open-Data-Issue-Tracker#21]
[State Real Property Register](https://riigivara.fin.ee/kvr/)'s open data is available in xml format at https://riigivara.fin.ee/lr1/web/guest/avaandmed

- schema: https://riigivara.fin.ee/kvr/avaandmed/schema
- properties: https://riigivara.fin.ee/kvr/avaandmed/kinnisvarad
- land parcels: https://riigivara.fin.ee/kvr/avaandmed/maad
- buildings: https://riigivara.fin.ee/kvr/avaandmed/hooned
- facilities: https://riigivara.fin.ee/kvr/avaandmed/rajatised
- proceedings: https://riigivara.fin.ee/kvr/avaandmed/menetlused
- agreements: https://riigivara.fin.ee/kvr/avaandmed/lepingud
- usage agreements: https://riigivara.fin.ee/kvr/avaandmed/kasutuslepingud

### File sizes

/20161030$ ls -lh
total 399M
11M Oct 30 11:56 hooned.xml
77M Oct 30 12:00 kasutuslepingud.xml
89M Oct 30 11:57 kinnisvarad.xml
29M Oct 30 11:59 lepingud.xml
76M Oct 30 11:56 maad.xml
111M Oct 30 11:59 menetlused.xml
6.9M Oct 30 11:57 rajatised.xml

About the register: https://www.riigiteataja.ee/en/eli/523012017002/consolide#para95
My GitHub repo (incl. buildings in GeoJSON): https://github.com/buildig/rkvr

**Comment by tormi** [comment]
@boamaod, it's official name in English is _State Real Property Register_, see https://www.riigiteataja.ee/en/eli/523012017002/consolide#para95 ;)

**Comment by andreskytt** [comment]
What's up with the issue? Is the point here that this should be listed in opendata.riik.ee? Close, if just informative. Thanks for the links!

**Comment by tormi** [comment]
Added for the viability ;)

**Comment by boamaod** [comment]
I think not being listed on opendata.riik.ee is a problem big enough to keep the issue open. I also think we should have our own list of open data sources, so instead of just closing an issue, we should add the links to that list.

**Comment by tormi** [comment]
> I think not being listed on opendata.riik.ee is a problem big enough to keep the issue open.

It is listed: https://opendata.riik.ee/et/dataset/kinnisvararegister
