### ISSUE TITLE
Readme (draft)

### ISSUE THREAD

**Issue by infokujur** [okestonia/Estonian-Open-Data-Issue-Tracker#23]
**Intro**

Estonian government agencies and local municipalities make datasets available in an open format – these are published in the government repository. https://opendata.riik.ee/et/data/search

In Estonian-Open-Data-Issue-Tracker repository, Open Knowledge Estonia is independently crowd-sourcing to learn about what kind of data people need to use and which open data should be available.

We believe that persons and organizations who use the data are in a strong position to advocate for more and higher quality open data. We have used Global Open Data Index as a model but we are adding categories that are not covered in Open Data Index. http://global.survey.okfn.org/

The Global Open Data Index tracks whether this data is actually released in a way that is accessible to citizens, media and civil society. OK-EE wants to give a crowd-sourced input to the global survey of open data releases. Contributions are welcome!

**Comment by infokujur** [comment]
**General plan**

Mapping first our situation for OpenData Index and then prioritize missing datasets, what could fill the gaps. This how we get initial demand list.
http://global.survey.okfn.org/

Extra input from the community.
Gather extra datasets what are not listed above and add to our demand list.

Collecting worldwide case studies (of opening the data) with financial impact evaluated
http://odimpact.org/
ex http://odimpact.org/case-denmarks-open-address-data-set.html
ex http://odimpact.org/case-opening-canadas-t3010-charity-information-return-data.html

**Comment by infokujur** [comment]
**For review and feedback:**

The 5 Stars guideline for linked open data is a way to measure how well data is integrated into the Web.
About 1-3 stars - https://www.europeandataportal.eu/elearning/en/module10/#/id/co-01
About 3-5 stars - https://www.europeandataportal.eu/elearning/en/module13/#/id/co-01

**Comment by infokujur** [comment]
**Next steps**

1. Shout out at Open Data day 04.03.207 https://www.facebook.com/events/1856419724613761/
2. Issue list cleaning 16.03 15:30 TLU, room A-428.

NB! Project ideas welcome! Tag them!

**Comment by infokujur** [comment]
http://5stardata.info/en/

**Comment by boamaod** [comment]
The text quoted here is also on wiki: https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker/wiki/About

How should we improve that and what we will use wiki for exactly?

**Comment by boamaod** [comment]
I'd suggest that we move successfully closed issues into Wiki, so it will become a sort of Open Data resources list?

**Comment by tormi** [comment]
I'm in favor of keeping that in readme, wiki pages are not that viable.

**Comment by tormi** [comment]
Could someone please add an empty readme.md so that we can start providing pull requests?

**Comment by boamaod** [comment]
@tormi Did it in commit 12fbc48

**Comment by tormi** [comment]
:+1: , I'd close this issue now and start follow-ups if needed. 

 > Isn't wiki also versioned somewhere and accessible as pure data?

Yes, GH wikis are also git instances, accessible from https://github.com/{org}/{repo}.wiki.git

**Comment by boamaod** [comment]
We need a policy for closing issues. I suggested that when we close a successful request for data, we document it in some human readable list. This makes it reasonable to file issues for cases when people find new data sources, that are not known and need to be registered somewhere. For example closing is issues like #21 shouldn't just happen like that, since we can use the data provided. Until opendata.riik.ee is not being managed and cleaned from municipal and other spam as described in https://github.com/opendata-ee/opendata.riik.ee/issues/7 it is meaningful to keep our own list, but even if national open data portal is perfect and managed, we might want to keep our own list to document also scraped data etc.

**Comment by tormi** [comment]
> I suggested that when we close a successful request for data, we document it in some human readable list.

What about https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker/issues/44#issuecomment-287082987 ?

**Comment by andreskytt** [comment]
That's a good idea. Done.

**Comment by tormi** [comment]
So I can close my bees and squirrels project then I guess :smile:

**Comment by infokujur** [comment]
@boamaod Can You propose solution for that list and open another issue for that topic if anything already proposed is not sufficent (like Open Data available silo etc).
