### ISSUE TITLE
Andmehulk Valimiste avalikud andmed viitab vanale allikale

### ISSUE THREAD

**Issue by SigritSiht** [okestonia/Estonian-Open-Data-Issue-Tracker#237]
https://opendata.riik.ee/andmehulgad/valimiste-avaandmed/ html ei ole enam aktiivne, kogu info eelnevate valimiste kohta on leitav menüüpunkti Valimiste arhiiv alt, mille URL on https://www.valimised.ee/et/toimunud-valimiste-arhiiv.

**Comment by keeganmcbride** [comment]
Didn't see this earlier, also addressed broken links here: https://github.com/okestonia/opendata.riik.ee/issues/621

**Comment by SigritSiht** [comment]
> Didn't see this earlier, also addressed broken links here: [okestonia/opendata.riik.ee#621](https://github.com/okestonia/opendata.riik.ee/issues/621)

If new broken links are to be discovered, should those be reported in that issue or it doesn't matter? Just FMI.

**Comment by keeganmcbride** [comment]
Probably in the open data issue tracker is correct, and I was wrong.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tkutsar** [comment]
Fixed the URL with PR 

https://github.com/okestonia/opendata.riik.ee/pull/911
