### ISSUE TITLE
Anti Corruption Open Data Principles

### ISSUE THREAD

**Issue by infokujur** [okestonia/Estonian-Open-Data-Issue-Tracker#24]
**Todo**:
- Identify (with label&refered to current issue) all datasets what are not open and are emphasized in introductory note.

Introductory note:
http://www.g20.utoronto.ca/2015/G20-Anti-Corruption-Open-Data-Principles.pdf

**Comment by andreskytt** [comment]
Let's try to keep labelling the issues as we go and do a review at each pruning

**Comment by infokujur** [comment]
#11 #8 #4 #32 #58
Referencing relevant issues what contribute to this topic and closing.
