### ISSUE TITLE
Turbauuringute andmebaas

### ISSUE THREAD

**Issue by HendrikHundt** [okestonia/Estonian-Open-Data-Issue-Tracker#242]
*	Turbauuringute andmebaas (dataset title in Estonian):
*	? (dataset title in English):
*	? (dataset description in Estonian):
*	? (dataset description in English):
*	Keskkond (Environment); 
*	? (Licence):
*	https://turba.geoloogia.info/ (Link to dataset):
*	Tallinna Tehnikaülikooli Geoloogia Instituut (organisation):
*	? (Update frequency):
*	? (date issued):
*	? (last modified):
*	Mall Orru, TalTechi geoloogia instituut (dataset maintainer):
*	mall.orru@taltech.ee  (maintainer’s e-mail):
*	? (maintainer’s phone):

**Comment by tkutsar** [comment]
Opened a pull request to create dataset: https://github.com/okestonia/opendata.riik.ee/pull/967/files

Application already available here: https://opendata.riik.ee/apps/TURBA/ 
Also fixed the organisation name on the application

**Comment by tkutsar** [comment]
Andmed portaali lisatud: https://opendata.riik.ee/andmehulgad/turbauuringute-andmebaas/

Datasets added to the portal: https://opendata.riik.ee/andmehulgad/turbauuringute-andmebaas/
