### ISSUE TITLE
National Statistics - Open Data Index

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/Estonian-Open-Data-Issue-Tracker#9]
Key national statistics on demographic and economic indicators such as Gross Domestic Product (GDP), or unemployment and population statistics.

- Gross Domestic Product
- National unemployment
- National population 

http://global.survey.okfn.org/dataset/statistics

**Comment by andreskytt** [comment]
Available at http://pub.stat.ee/px-web.2001/dialog/statfile2.asp Close if sufficient

**Comment by andreskytt** [comment]
Closing, can't imagine much more data being made available
